datasource.url=jdbc:mysql://localhost:3306/dende_eventos?useSSL=false&serverTimezone=UTC
datasource.username=
datasource.password=
datasource.driver-class-name=com.mysql.cj.jdbc.Driver

datasource.hikari.maximum-pool-size=10
datasource.hikari.minimum-idle=2
datasource.hikari.connection-timeout=30000